FROM golang:1.25-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o redirect_svc ./cmd/api

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/redirect_svc .

CMD [ "./redirect_svc" ]
