FROM golang:1.24-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . . 

RUN go build -o url_shortener_svc ./cmd/api

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/url_shortener_svc .

CMD [ "./url_shortener_svc" ]
