// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getByShortCode = `-- name: GetByShortCode :one
SELECT id,original_url,short_code,created_at FROM urls WHERE short_code = $1
`

func (q *Queries) GetByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}

const saveURL = `-- name: SaveURL :one
INSERT INTO urls(original_url,short_code) VALUES($1,$2) RETURNING id,created_at
`

type SaveURLParams struct {
	OriginalUrl string
	ShortCode   string
}

type SaveURLRow struct {
	ID        int64
	CreatedAt sql.NullTime
}

func (q *Queries) SaveURL(ctx context.Context, arg SaveURLParams) (SaveURLRow, error) {
	row := q.db.QueryRowContext(ctx, saveURL, arg.OriginalUrl, arg.ShortCode)
	var i SaveURLRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
