apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: "shortly"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  VALKEY_HOST: "valkey"
  VALKEY_PORT: "6379"
  VALKEY_USERNAME: "default"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  KRAKEND_GATEWAY_PORT: "8080"
  URL_SHORTENER_SVC_PORT: "8080"
  URL_SHORTENER_SVC_GRPC_PORT: "50051"
  REDIRECT_SVC_PORT: "8080"
  REDIRECT_SVC_GRPC_PORT: "50052"
  URL_SHORTENER_SVC_HOST: "shortener-svc"
  REDIRECT_SVC_HOST: "redirect-svc"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password"
  VALKEY_PASSWORD: "valkey_password"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
