apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-svc
  template:
    metadata:
      labels:
        app: shortener-svc
    spec:
      containers:
        - name: shortener-svc
          image: shortener_svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: shortener-svc
spec:
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 50051
  selector:
    app: shortener-svc
