// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: protos/common.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalitycsService_TrackEvent_FullMethodName = "/proto.AnalitycsService/TrackEvent"
)

// AnalitycsServiceClient is the client API for AnalitycsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalitycsServiceClient interface {
	TrackEvent(ctx context.Context, in *TrackEventRequest, opts ...grpc.CallOption) (*TrackEventResponse, error)
}

type analitycsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalitycsServiceClient(cc grpc.ClientConnInterface) AnalitycsServiceClient {
	return &analitycsServiceClient{cc}
}

func (c *analitycsServiceClient) TrackEvent(ctx context.Context, in *TrackEventRequest, opts ...grpc.CallOption) (*TrackEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackEventResponse)
	err := c.cc.Invoke(ctx, AnalitycsService_TrackEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalitycsServiceServer is the server API for AnalitycsService service.
// All implementations must embed UnimplementedAnalitycsServiceServer
// for forward compatibility.
type AnalitycsServiceServer interface {
	TrackEvent(context.Context, *TrackEventRequest) (*TrackEventResponse, error)
	mustEmbedUnimplementedAnalitycsServiceServer()
}

// UnimplementedAnalitycsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalitycsServiceServer struct{}

func (UnimplementedAnalitycsServiceServer) TrackEvent(context.Context, *TrackEventRequest) (*TrackEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackEvent not implemented")
}
func (UnimplementedAnalitycsServiceServer) mustEmbedUnimplementedAnalitycsServiceServer() {}
func (UnimplementedAnalitycsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalitycsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalitycsServiceServer will
// result in compilation errors.
type UnsafeAnalitycsServiceServer interface {
	mustEmbedUnimplementedAnalitycsServiceServer()
}

func RegisterAnalitycsServiceServer(s grpc.ServiceRegistrar, srv AnalitycsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalitycsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalitycsService_ServiceDesc, srv)
}

func _AnalitycsService_TrackEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalitycsServiceServer).TrackEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalitycsService_TrackEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalitycsServiceServer).TrackEvent(ctx, req.(*TrackEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalitycsService_ServiceDesc is the grpc.ServiceDesc for AnalitycsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalitycsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AnalitycsService",
	HandlerType: (*AnalitycsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackEvent",
			Handler:    _AnalitycsService_TrackEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/common.proto",
}
