// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: shortener_svc.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_shortener_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_shortener_svc_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawUrl        string                 `protobuf:"bytes,1,opt,name=raw_url,json=rawUrl,proto3" json:"raw_url,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_shortener_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_shortener_svc_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLResponse) GetRawUrl() string {
	if x != nil {
		return x.RawUrl
	}
	return ""
}

func (x *GetURLResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_shortener_svc_proto protoreflect.FileDescriptor

const file_shortener_svc_proto_rawDesc = "" +
	"\n" +
	"\x13shortener_svc.proto\x12\x06protos\"#\n" +
	"\rGetURLRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"=\n" +
	"\x0eGetURLResponse\x12\x17\n" +
	"\araw_url\x18\x01 \x01(\tR\x06rawUrl\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code2L\n" +
	"\x06GetURL\x12B\n" +
	"\x11GetURLByShortCode\x12\x15.protos.GetURLRequest\x1a\x16.protos.GetURLResponseB(Z&github.com/FreyreCorona/Shortly/protosb\x06proto3"

var (
	file_shortener_svc_proto_rawDescOnce sync.Once
	file_shortener_svc_proto_rawDescData []byte
)

func file_shortener_svc_proto_rawDescGZIP() []byte {
	file_shortener_svc_proto_rawDescOnce.Do(func() {
		file_shortener_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_svc_proto_rawDesc), len(file_shortener_svc_proto_rawDesc)))
	})
	return file_shortener_svc_proto_rawDescData
}

var file_shortener_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shortener_svc_proto_goTypes = []any{
	(*GetURLRequest)(nil),  // 0: protos.GetURLRequest
	(*GetURLResponse)(nil), // 1: protos.GetURLResponse
}
var file_shortener_svc_proto_depIdxs = []int32{
	0, // 0: protos.GetURL.GetURLByShortCode:input_type -> protos.GetURLRequest
	1, // 1: protos.GetURL.GetURLByShortCode:output_type -> protos.GetURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortener_svc_proto_init() }
func file_shortener_svc_proto_init() {
	if File_shortener_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_svc_proto_rawDesc), len(file_shortener_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_svc_proto_goTypes,
		DependencyIndexes: file_shortener_svc_proto_depIdxs,
		MessageInfos:      file_shortener_svc_proto_msgTypes,
	}.Build()
	File_shortener_svc_proto = out.File
	file_shortener_svc_proto_goTypes = nil
	file_shortener_svc_proto_depIdxs = nil
}
