// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Url struct {
	ID          int64
	OriginalUrl string
	ShortCode   string
	CreatedAt   sql.NullTime
}
