apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  VALKEY_HOST: "valkey"
  VALKEY_PORT: {{ .Values.valkey.port | quote }}
  VALKEY_USERNAME: "default"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  KRAKEND_GATEWAY_PORT: {{ .Values.krakend.port | quote }}
  URL_SHORTENER_SVC_PORT: {{ .Values.shortener.httpPort | quote }}
  URL_SHORTENER_SVC_GRPC_PORT: {{ .Values.shortener.grpcPort | quote }}
  REDIRECT_SVC_PORT: {{ .Values.redirect.httpPort | quote }}
  REDIRECT_SVC_GRPC_PORT: {{ .Values.redirect.grpcPort | quote }}
  URL_SHORTENER_SVC_HOST: "shortener-svc"
  REDIRECT_SVC_HOST: "redirect-svc"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  VALKEY_PASSWORD: {{ .Values.valkey.password | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | quote }}
