apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_HOST: {{ if .Values.postgres.enabled }}"postgres"{{ else }}{{ .Values.postgres.external.host | quote }}{{ end }}
  POSTGRES_PORT: {{ if .Values.postgres.enabled }}{{ .Values.postgres.port | quote }}{{ else }}{{ .Values.postgres.external.port | quote }}{{ end }}
  VALKEY_HOST: {{ if .Values.valkey.enabled }}"valkey"{{ else }}{{ .Values.valkey.external.host | quote }}{{ end }}
  VALKEY_PORT: {{ if .Values.valkey.enabled }}{{ .Values.valkey.port | quote }}{{ else }}{{ .Values.valkey.external.port | quote }}{{ end }}
  VALKEY_USERNAME: "default"
  RABBITMQ_HOST: {{ if .Values.rabbitmq.enabled }}"rabbitmq"{{ else }}{{ .Values.rabbitmq.external.host | quote }}{{ end }}
  RABBITMQ_PORT: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.port | quote }}{{ else }}{{ .Values.rabbitmq.external.port | quote }}{{ end }}
  KRAKEND_GATEWAY_PORT: {{ .Values.krakend.port | quote }}
  URL_SHORTENER_SVC_PORT: {{ .Values.shortener.httpPort | quote }}
  URL_SHORTENER_SVC_GRPC_PORT: {{ .Values.shortener.grpcPort | quote }}
  REDIRECT_SVC_PORT: {{ .Values.redirect.httpPort | quote }}
  REDIRECT_SVC_GRPC_PORT: {{ .Values.redirect.grpcPort | quote }}
  URL_SHORTENER_SVC_HOST: "shortener-svc"
  REDIRECT_SVC_HOST: "redirect-svc"
  METRICS_PORT: {{ .Values.shortener.metricsPort | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ if .Values.postgres.enabled }}{{ .Values.postgres.user | quote }}{{ else }}{{ .Values.postgres.external.user | quote }}{{ end }}
  POSTGRES_PASSWORD: {{ if .Values.postgres.enabled }}{{ .Values.postgres.password | quote }}{{ else }}{{ .Values.postgres.external.password | quote }}{{ end }}
  VALKEY_PASSWORD: {{ .Values.valkey.password | quote }}
  RABBITMQ_DEFAULT_USER: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.user | quote }}{{ else }}{{ .Values.rabbitmq.external.user | quote }}{{ end }}
  RABBITMQ_DEFAULT_PASS: {{ if .Values.rabbitmq.enabled }}{{ .Values.rabbitmq.password | quote }}{{ else }}{{ .Values.rabbitmq.external.password | quote }}{{ end }}