FROM golang:1.24-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o analitycs_svc ./cmd/api

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/analitycs_svc .

CMD [ "./analitycs_svc"]
